services:
  - type: web
    name: spam-detector
    env: pythongit init
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
